development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://celtiachat.herokuapp.com/faye"
  secret_token: "de88ec264023dc167f35e453281f48908f18af9ec4302bd63e2b6ee7a09c86f1"
  signature_expiration: 86400 # one day
